export const APP_CONFIG_TOKEN = Symbol("APP_CONFIG_TOKEN");
export const PRISMA_CLIENT_TOKEN = Symbol("PRISMA_CLIENT_TOKEN");
export const SENSOR_REPOSITORY_TOKEN = Symbol("SENSOR_REPOSITORY_TOKEN");
export const SENSOR_CACHE_TOKEN = Symbol("SENSOR_CACHE_TOKEN");
export const DEVICE_COMMAND_SENDER_TOKEN = Symbol("DEVICE_COMMAND_SENDER_TOKEN");
export const DEVICE_ACTIVITY_READER_TOKEN = Symbol("DEVICE_ACTIVITY_READER_TOKEN");
export const DEVICE_STATE_READER_TOKEN = Symbol("DEVICE_STATE_READER_TOKEN");
export const FIREBASE_AUTH_VERIFIER_TOKEN = Symbol("FIREBASE_AUTH_VERIFIER_TOKEN");
