name: Dart CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: ./first_lab

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --set-exit-if-changed .

      - name: Run Analysis
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          working-directory: ./first_lab
